### ISSUE TITLE
运行时出现错误：KeyError: 'content'

### ISSUE THREAD

**Issue by WenHe233** [nfe-w/bili_dynamic_downloader#1]
> Traceback (most recent call last):
  File "F:\Vtuber\皆守\bili_dynamic_downloader\bili_dynamic_downloader.py", line 169, in <module>
    real_main()
  File "F:\Vtuber\皆守\bili_dynamic_downloader\bili_dynamic_downloader.py", line 165, in real_main
    download_pic(save_dir, obj_array)
  File "F:\Vtuber\皆守\bili_dynamic_downloader\bili_dynamic_downloader.py", line 134, in download_pic
    if item['item']['content'] is not None:
KeyError: 'content'

运行配置：

> uid = 395814787  # 用户uid
need_download = True  # 是否下载动态
skip_forward_and_video = False  # 是否跳过转发动态和视频投稿的封面
skip_text_only = False  # 是否跳过纯文字动态

似乎是处理视频动态时会出现问题。

**Comment by nfe-w** [comment]
拉下代码，已修复完毕 7520b2fed20365ce3059f892c3b9ea2eaf13ea64
